const weatherIcons = {
  "clear sky": "☀️",
  "few clouds": "🌤️",
  "scattered clouds": "🌥️",
  "broken clouds": "☁️",
  "overcast clouds": "☁️",
  "light rain": "🌦️",
  "moderate rain": "🌧️",
  "heavy intensity rain": "🌧️",
  "very heavy rain": "🌧️",
  "freezing rain": "🧊🌧️",
  "light intensity drizzle": "🌦️",
  drizzle: "🌦️",
  "heavy intensity drizzle": "🌦️",
  "thunderstorm with light rain": "⛈️",
  "thunderstorm with heavy rain": "⛈️",
  "thunderstorm with hail": "⛈️❄️",
  "light snow": "🌨️",
  snow: "❄️",
  "heavy snow": "❄️❄️",
  sleet: "🌨️❄️",
  mist: "🌫️",
  smoke: "💨",
  haze: "🌫️",
  "sand/dust whirls": "🌪️",
  dust: "🌪️",
  fog: "🌫️",
  sand: "🏜️",
  "volcanic ash": "🌋",
  squalls: "💨",
  tornado: "🌪️",
};

export default weatherIcons;
